"use strict";
var path = require("path");
var cssPrepareStep = require("./grunt_utils/modules/cssPrepareStep");
var requirejsPrepareStep = require("./grunt_utils/modules/requirejsPrepareStep");
var browserifyPrepareStep = require("./grunt_utils/modules/browserifyPrepareStep");
var sourceMapNameGen = require("./grunt_utils/modules/sourceMapNameGen");
var sourceMapURLGen = require("./grunt_utils/modules/sourceMapURLGen");
var replaceSuffix = require("./grunt_utils/modules/replaceSuffix");

module.exports = function(grunt) {
    /**
     * Feel free to configure app, copy:assets, copy:dev, copy:qa, copy:prd
     * targets. Only edit the others if you know what you are doing.
     */
    grunt.initConfig({
        "app": {
            src: "src",
            dist: "dist",
            bower: "bower_components",
            staging: ".tmp",
            configDir: "config",
            configSrcDir: "build"
        },
        "copy": {
            assets: {
                files: [{
                        expand: true,
                        cwd: "<%= app.src %>",
                        src: ["assets/**", "images/**", "fonts/**"],
                        dest: "<%= app.dist %>"
                    }, {
                        expand: true,
                        cwd: "<%= app.bower %>/bootstrap/dist",
                        src: ["fonts/**"],
                        dest: "<%= app.dist %>"
                    }
                ]
            },
            dev: {
                files: [{
                        expand: true,
                        cwd: "<%= app.src %>/<%= app.configSrcDir %>/<%= app.configDir %>-dev",
                        src: ["**"],
                        dest: "<%= app.src %>/<%= app.configDir %>"
                    }
                ]
            },
            qa: {
                files: [{
                        expand: true,
                        cwd: "<%= app.src %>/<%= app.configSrcDir %>/<%= app.configDir %>-qa",
                        src: ["**"],
                        dest: "<%= app.src %>/<%= app.configDir %>"
                    }
                ]
            },
            prd: {
                files: [{
                        expand: true,
                        cwd: "<%= app.src %>/<%= app.configSrcDir %>/<%= app.configDir %>-prd",
                        src: ["**"],
                        dest: "<%= app.src %>/<%= app.configDir %>"
                    }
                ]
            },
            htmlrefs: {
                files: [{
                        expand: true,
                        cwd: "<%= app.src %>",
                        src: ["**/*.html"],
                        dest: "<%= app.src %>",
                        ext: ".htmlrefs"
                    }
                ]
            },
            html: {
                files: [{
                        expand: true,
                        cwd: "<%= app.src %>",
                        src: ["**/*.htmlrefs"],
                        dest: "<%= app.dist %>",
                        ext: ".html"
                    }
                ]
            },
            jsSourceMap: {}
        },
        "htmlrefs": {
            build: {
                src: ["<%= app.src %>/**/*.htmlrefs"]
            }
        },
        "useminPreparePrepare": {
            html: "<%= app.src %>/**/*.htmlrefs",
            options: {
                src: "<%= app.src %>",
                dest: "<%= app.dist %>",
                staging: "<%= app.staging %>",
                flow: {
                    steps: {
                        "js": ["uglifyjs"],
                        "css": [cssPrepareStep, "cssmin"],
                        "amd": [requirejsPrepareStep, "uglifyjs"],
                        "commonjs": [browserifyPrepareStep, "uglifyjs"]
                    },
                    post: {}
                }
            }
        },
        "requirejsPrepare": {
            generated: {
                // Options will be copied to requirejs options. baseUrl,
                // mainConfigFile, name and out properties will be automatically
                // generated by this task. However if define them here, they
                // will be override. Paths will be normalized from baseUrl so
                // that you can define it here relative to Gruntfile.js If you
                // MUST have more than one target, use configFilesToTarget to
                // copy files generated by useminPrepare to another target then
                // you will be able to run targets other than generated.
                options: {
                    optimize: "none",
                    paths: {
                        requireLib: "bower_components/almond/almond"
                    },
                    include: "requireLib"
                }
            }
        },
        "browserifyPrepare": {
            // If you MUST have more than one target, use configFilesToTarget to
            // copy files generated by useminPrepare to another target then you
            // will be able to run targets other than generated. Options will be
            // copied straight to browserify task.
            generated: {},
        },
        "replaceUseminType": {
            generated: {
            }
        },
        "usemin": {
            html: ["<%= app.dist %>/**/*.html"],
            options: {
                assetsDirs: ["<%= app.dist %>"]
            }
        },
        "configFilesToTarget": {
            genSourceMap: {
                options: {
                    targets: ["genSourceMap"],
                    tasks: ["uglify"]
                }
            }
        },
        "uglify": {
            options: {
                preserveComments: "some"
            },
            genSourceMap: {
                options: {
                    // Due to the way uglify works, source path is pretty messed
                    // up. Please keep that in mind.
                    sourceMap: sourceMapNameGen,
                    sourceMappingURL: sourceMapURLGen
                }
            }
        },
        "cssPrepare": {
            generated: {}
        },
        "cssmin": {
            generated: {},
            options: {
                keepSpecialComments: "*"
            }
        },
        "htmlmin": {
            build: {
                options: {
                    removeComments: true,
                    collapseWhitespace: true
                },
                files: [{
                    expand: true,
                    dest: ".",
                    src: ["<%= app.dist %>/**/*.html"]
                }]
            }
        },
        "sourceCopyPrepare": {
            jsSourceMap: {
                options: {
                    srcTask: "uglify",
                    srcTaskTarget: "genSourceMap"
                }
            }
        },
        "configToTask": {
            uglifyToConcat: {
                options: {
                    from: "uglify",
                    to: "concat"
                }
            }
        },
        "clean": {
            postBuild: ["<%= app.staging %>", "<%= app.src %>/**/*.htmlrefs"],
            clean: ["<%= app.dist %>", "<%= app.src %>/<%= app.configDir %>"]
        },
        "watch": {
            devCommonJs: {
                files: [
                    "<%= app.src %>/**/*",
                    "!<%= app.src %>/**/*.htmlrefs",
                    // Don't forget to add your config directory to ignore list.
                    // If you don't have a config directory, remove this line.
                    "!<%= app.src %>/<%= app.configDir %>/**/*"
                ],
                tasks: ["devCommonJs"],
                options: {
                    interrupt: true
                }
            },
            // This target can be used when you actively changing configs,
            // otherwise it's pretty pointless.
            dev: {
                files: [
                    "<%= app.src %>/<%= app.configSrcDir %>/**/*"
                ],
                tasks: ["dev"],
                options: {
                    interrupt: true
                }
            }
        }
    });

    grunt.loadTasks("grunt_utils/tasks");

    grunt.loadNpmTasks("grunt-usemin");
    grunt.loadNpmTasks("grunt-contrib-copy");
    grunt.loadNpmTasks("grunt-contrib-uglify");
    grunt.loadNpmTasks("grunt-contrib-less");
    grunt.loadNpmTasks("grunt-contrib-sass");
    grunt.loadNpmTasks("grunt-contrib-cssmin");
    grunt.loadNpmTasks('grunt-contrib-htmlmin');
    grunt.loadNpmTasks("grunt-htmlrefs");
    grunt.loadNpmTasks('grunt-contrib-concat');
    grunt.loadNpmTasks("grunt-contrib-clean");
    grunt.loadNpmTasks('grunt-contrib-watch');

    grunt.registerTask("prebuild", [
        "copy:htmlrefs",
        "htmlrefs:build",
        "copy:html",
        "copy:assets",
        "useminPreparePrepare",
        "useminPrepare"
    ]);

    grunt.registerTask("amdGen", [
        "requirejsPrepare:generated"
    ]);

    grunt.registerTask("commonJsGen", [
        "browserifyPrepare:generated"
    ]);

    grunt.registerTask("cssGen", [
        "cssPrepare:generated",
        "copy:generated",
        "less:generated",
        "sass:generated"
    ]);

    grunt.registerTask("minExternal", [
        "uglify:generated",
        "cssmin:generated"
    ]);

    // Too bad there's no source map gen for CSS with grunt-contrib-cssmin.
    grunt.registerTask("minExternalGenSourceMap", [
        "configFilesToTarget:genSourceMap",
        "uglify:genSourceMap",
        "cssmin:generated",
        "sourceCopyPrepare:jsSourceMap",
        "copy:jsSourceMap"
    ]);

    grunt.registerTask("useminWrapped", [
        "replaceUseminType:generated",
        "usemin"
    ]);

    grunt.registerTask("finalize", [
        "clean:postBuild"
    ]);

    grunt.registerTask("buildAll", [
        "prebuild",
        "amdGen",
        "commonJsGen",
        "cssGen",
        "minExternal",
        "useminWrapped",
        "htmlmin:build",
        "finalize"
    ]);

    grunt.registerTask("buildGenSourceMap", [
        "prebuild",
        "amdGen",
        "commonJsGen",
        "cssGen",
        "minExternalGenSourceMap",
        "useminWrapped",
        "htmlmin:build",
        "finalize"
    ]);

    /****************** Actual tasks you should use to build ******************/

    grunt.registerTask("dev", [
        "copy:dev"
    ]);

    // This is a special dev build task aimed for projects developed with
    // CommonJS. Due to the fact that CommonJS modules are not browser
    // compatible in their raw forms, in order to run them in a browser, they
    // must be processed by browserify. This task runs the minimun amount of
    // process to help wrap CommonJS modules and get them to a runnable state.
    // That also means you will have to run your project from dist directory
    // instead. See watch task for better convenience.
    grunt.registerTask("devCommonJs", [
        "copy:dev",
        "prebuild",
        "commonJsGen",
        "cssGen",
        "configToTask:uglifyToConcat",
        "concat:generated",
        "useminWrapped",
        "finalize"
    ]);

    grunt.registerTask("prd", [
        "clean",
        "copy:prd",
        "buildAll"
    ]);

    grunt.registerTask("qa", [
        "clean",
        "copy:qa",
        "buildGenSourceMap"
    ]);

    grunt.registerTask("default", ["dev"]);
}
